Refactor to compress to tar.gz before uploading

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -21,29 +21,24 @@ if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then
   fi
 
   bucket="${BUILDKITE_PLUGIN_CACHE_S3_BUCKET_NAME}/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/${cache_key}"
-  
+
   paths=()
-  
-  if [[ -n "${BUILDKITE_PLUGIN_CACHE_PATHS:-}" ]] ; then
-    paths+=("$BUILDKITE_PLUGIN_CACHE_PATHS")
-  fi
-  
   while IFS='=' read -r path _ ; do
     if [[ $path =~ ^(BUILDKITE_PLUGIN_CACHE_PATHS_[0-9]+) ]] ; then
       paths+=("${!path}")
     fi
-  done < <(env | sort)
-  
-  if [ "${#paths[@]}" -eq 1 ]; then
+  done < <(env | sort | grep BUILDKITE_PLUGIN_CACHE_PATHS_)
 
-    echo "--- :aws: :amazon-s3: sync ${paths[*]}"
-    aws s3 sync "${paths[*]}" "s3://${bucket}/${paths[*]}/" --profile="${BUILDKITE_PLUGIN_CACHE_S3_PROFILE}" --delete    
+  tmpdir=$(mktemp -d)
+  if [[ "${BUILDKITE_PLUGIN_CACHE_RESTORED:-}" == *":$cache_key:"* ]]; then
+    echo "Not uploading new cache - it was restored"
+    exit 0
+  fi
 
-  elif [ "${#paths[@]}" -gt 1 ]; then
-    for path in "${paths[@]}"
-      do
-        echo "--- :aws: :amazon-s3: sync ${path}"
-        aws s3 sync "${path}" "s3://${bucket}/${path}/" --profile="${BUILDKITE_PLUGIN_CACHE_S3_PROFILE}" --delete
-      done
-  fi  
+  echo "Compressing cache for $cache_key"
+  tar -czf $tmpdir/cache.tar.gz ${paths[@]} || echo "tar failed"
+
+  echo "Saving cache ${cache_key}"
+  aws s3 sync "$tmpdir/" "s3://${bucket}/" --delete
+  rm -rf $tmpdir
 fi
diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -6,6 +6,11 @@ if [[ "${BUILDKITE_PLUGIN_CACHE_DEBUG:-false}" =~ (true|on|1) ]] ; then
   set -x
 fi
 
+function mark_restored() {
+  echo "Successfully restored $1"
+  export BUILDKITE_PLUGIN_CACHE_RESTORED=${BUILDKITE_PLUGIN_CACHE_RESTORED:-}:$1:
+}
+
 if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then
 
   cache_key_prefix=$(echo "$BUILDKITE_PLUGIN_CACHE_CACHE_KEY" | sed -e 's/{.*//')
@@ -20,10 +25,12 @@ if [[ -n "${BUILDKITE_PLUGIN_CACHE_CACHE_KEY:-}" ]] ; then
     cache_key=$BUILDKITE_PLUGIN_CACHE_CACHE_KEY
   fi
 
-  echo ":aws: :amazon-s3: sync ${cache_key}"
-  
+  echo "Restoring cache ${cache_key}"
+
   bucket="${BUILDKITE_PLUGIN_CACHE_S3_BUCKET_NAME}/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}/${cache_key}"
-  
-  aws s3 sync "s3://${bucket}/" . --profile="${BUILDKITE_PLUGIN_CACHE_S3_PROFILE}"
-    
+  tmpdir=$(mktemp -d)
+  aws s3 sync "s3://${bucket}/" $tmpdir/.
+  # Set env var if we loaded the cache so we can skip reuploading it
+  tar -xzf $tmpdir/cache.tar.gz && mark_restored $cache_key || echo "Cache not found"
+  rm -rf $tmpdir
 fi
